version: "3.9"

services:
    database_finapi:
        image: postgres
        container_name: database_finapi
        restart: always
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=docker
            - POSTGRES_DB=finapi
        volumes:
            - pgdata:/data/postgres

volumes:
    pgdata:
        driver: local
